### ISSUE TITLE
Runner has issues with its JSON checkbox

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#890] opened 2021-05-03 06:56 UTC
@schuelet I was wondering why the one RAKIP model is always failing in the test run, even if you state correctly it is working fine in other workflows. Therefore, I thought that should be investigated and found out that I am using as requested the JSON checkbox selected in my testworkflow which leads to the fail without a useful error message on the server.

Interestingly, I need to use a new node to see that the node fully executes if the checkbox is not selected. That is indicating that the checkbox feature has an issue and on top it seems to remember that issue since unchecking does not help afterwards - it requires a new runner node to show that.

Here is the example workflow. knime://knime.mountpoint/FSKX_Testing/FSK-Lab_2.0/broken_workflows/Run_local_model_test_P2_FSK2.0_runner_issue

**Comment by schuelet** [comment] 2021-05-03 10:14
@llavall Thanks for the findings:
- I modified the error message so that they appear on the server as well.
- I still like that the model fails if something is wrong the the parameter scope like in the above example, provided the user wants to make use of the parameter.json file or join the model
- The checkbox issue I could not reproduce, I tested on Windows and Debian. Could you double check please?

**Comment by llavall** [comment] 2021-05-03 10:52
@schuelet I still see the described checkbox issue in Windows and on the server - but on the server I can not change the checkbox live - the option does not appear. If you want to we can look at it together in a webmeeting .

**Comment by llavall** [comment] 2021-05-03 13:02
@mfilter Thomas and I where looking at the checkbox issue. The runner still fails if for that given model a JSON output was selected. Thomas explained that the parameters declared in that model are not really output parameter (they just exist inside of a R function) and therefor the JSON-part can not write it out. Therefore, the model needs to be adjusted in oder to pass my testworkflow.

Unfortunately, I was not able anymore to show the remember checkbox selected issue.

Instead, the problem that the config menu can not be accesed on the server seems to be a bug and needs to be investigated - fpr the reader it is working.

**Comment by schuelet** [comment] 2022-06-30 13:11
issue related to a deprecated model (not available under above mentioned name).

closing this issue.

**Closed by schuelet** 2022-06-30 13:11 UTC
