### ISSUE TITLE
Marcel Editor 2: edited parameters are not stored in fsk-object at outport

### ISSUE THREAD

**Issue by Thatsreallycool** [SiLeBAT/FSK-Lab#875] opened 2021-04-26 12:31 UTC
update site: fsktest - https://dl.bintray.com/silebat/test2

When editing the list of parameters via Editor, adding new parameters or renaming existing parameters does not update the outgoing fsk-object. A Runner runs the model with the old set of parameters and values

uploaded a test workflow for this behaviour
knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/broken_workflows/editor_renaming_parameters

**Comment by schuelet** [comment] 2021-04-26 13:16
@Thatsreallycool In the current version, this does not happen. Try using the new BfR update site:
https://gitlab.bfr.berlin/silebat/repositories/raw/master/fsklab/

Here is the modified workflow (reset may be necessary):
knime://external-KNIME-Server/FSKX_Testing/FSK-Lab_2.0/fixed_broken_workflows/editor_renaming_parameters_TS

**Comment by Thatsreallycool** [comment] 2021-04-26 16:33
Tested it, and it works fine with this build. Thanks!

**Comment by Thatsreallycool** [comment] 2021-04-28 15:54
update site: https://gitlab.bfr.berlin/silebat/repositories/raw/master/fsklab/

With the newest update, this bug occured again. 
Added new parameters via Editor, Runner cannot "see" them. Saved Model with Writer. 
Then used the reader to load the file. Still, the reader is not able to load the new set of parameters. But when the Editor is opened, all new parameters are present.

Workflow provided in:
knime://BfR-extern/FSKX_Testing/FSK-Lab_2.0/broken_workflows/Marcel_editor_adding_new_parameters

**Comment by mfilter** [comment] 2021-04-28 18:13
@Thatsreallycool : could you please explain which parameter you added that are not visible in the Reader? That would help others to reproduce your findings.

**Comment by mfilter** [comment] 2021-04-28 18:28
I can confirm the findings. A side-note: many of the new parameters are defined as "Constant"s. So I would not expect those to be listed in a the simulations, but all the others. I assume one needs to trigger the creation of the simulation scenarios every time the editor is closed.

**Comment by Thatsreallycool** [comment] 2021-04-29 06:27
> 
> 
> I can confirm the findings. A side-note: many of the new parameters are defined as "Constant"s. So I would not expect those to be listed in a the simulations, but all the others. I assume one needs to trigger the creation of the simulation scenarios every time the editor is closed.

Just a quick side note for clarity: According to the errorlog of the runner,  both newly added parameter types (const and input) are not found, when applying the runner.

For clarity purposes i added to the workflow description a note about which of the new parameters are const and which are input, in case it is needed.

**Comment by mfilter** [comment] 2021-05-01 09:37
I just tested the workflow from Marcel again and added some nodes here to explain my findings
knime://BfR-extern/FSKX_Testing/FSK-Lab_2.0/broken_workflows/Marcel_editor_adding_new_parameters_MF 
There are still issues.

1: after execution of the editors the new parameters are still not visible in the outport object of the node. This also propagates to the next node, e.g. the Runner.
2.: when I connect a Simulation Configurator JS node to the outport of the Editor I see, that in there the new parameters are included in all the simulations. The problem is, that for those new parameters the values are not available, e.g. the default values provided in the Editor. After execution of the Simulation Configurator the simulations is then also correctly available on the Java side.

**Comment by schuelet** [comment] 2022-06-30 13:17
fixed in SiLeBAT/FSK-Lab#884

**Closed by schuelet** 2022-06-30 13:17 UTC
Labels: high priority
