### ISSUE TITLE
de.bund.bfr.knime.internal.feature.feature.group still does not work

### ISSUE THREAD

**Issue by llavall** [SiLeBAT/FSK-Lab#265] opened 2018-10-06 14:20 UTC
`
failed: [knime02.bfr.berlin] (item=de.bund.bfr.knime.internal.feature.feature.group) => {"changed": true, "cmd": "/opt/knime_server/knime_executor/knime -nosplash -application org.eclipse.equinox.p2.director -profile KNIMEProfile -destination /opt/knime_server/knime_executor -repository http://update.knime.org/analytics-platform/3.6,http://update.knime.org/store/3.6,http://update.knime.org/community-contributions/trusted/3.6,http://update.knime.org/community-contributions/3.6,http://update.knime.org/community-contributions/3.6,https://dl.bintray.com/silebat/fsklab_icpmf,https://github.com/SiLeBAT/Other/raw/master/de.bund.bfr.knime.other.aaw.feat/update,https://dl.bintray.com/silebat/pmmlab,http://dl.bintray.com/silebat/generic,http://dl.bintray.com/silebat/internal/ -installIU de.bund.bfr.knime.internal.feature.feature.group && touch /opt/knime_server/knime_executor/plugins/de.bund.bfr.knime.internal.feature.feature.group.installed", "delta": "0:00:40.204601", "end": "2018-10-06 16:17:50.257744", "item": "de.bund.bfr.knime.internal.feature.feature.group", "msg": "non-zero return code", "rc": 13, "start": "2018-10-06 16:17:10.053143", "stderr": "Oct 06, 2018 4:17:24 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions\nINFO: Adding the extensions from bundle org.apache.cxf.cxf-rt-transports-http (298) [org.apache.cxf.transport.http.HTTPTransportFactory, org.apache.cxf.transport.http.HTTPWSDLExtensionLoader, org.apache.cxf.transport.http.policy.HTTPClientAssertionBuilder, org.apache.cxf.transport.http.policy.HTTPServerAssertionBuilder, org.apache.cxf.transport.http.policy.NoOpPolicyInterceptorProvider]\nOct 06, 2018 4:17:24 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions\nINFO: Adding the extensions from bundle org.apache.cxf.cxf-rt-transports-http-hc (299) [org.apache.cxf.transport.http.HTTPConduitFactory, org.apache.cxf.transport.ConduitInitiator]\nCannot complete the install because one or more required items could not be found.\n Software being installed: BfR Internal Feature 1.0.0.201807201155 (de.bund.bfr.knime.internal.feature.feature.group 1.0.0.201807201155)\n Missing requirement: BfR Internal Feature 1.0.0.201807201155 (de.bund.bfr.knime.internal.feature.feature.group 1.0.0.201807201155) requires 'de.bund.br.knime.nodes.util 0.0.0' but it could not be found\nApplication failed, log file location: /opt/knime_server/knime_executor/configuration/1538835430342.log\nOct 06, 2018 4:17:49 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener unregister\nINFO: Removing the extensions for bundle 298\nOct 06, 2018 4:17:49 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener unregister\nINFO: Removing the extensions for bundle 299", "stderr_lines": ["Oct 06, 2018 4:17:24 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions", "INFO: Adding the extensions from bundle org.apache.cxf.cxf-rt-transports-http (298) [org.apache.cxf.transport.http.HTTPTransportFactory, org.apache.cxf.transport.http.HTTPWSDLExtensionLoader, org.apache.cxf.transport.http.policy.HTTPClientAssertionBuilder, org.apache.cxf.transport.http.policy.HTTPServerAssertionBuilder, org.apache.cxf.transport.http.policy.NoOpPolicyInterceptorProvider]", "Oct 06, 2018 4:17:24 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener addExtensions", "INFO: Adding the extensions from bundle org.apache.cxf.cxf-rt-transports-http-hc (299) [org.apache.cxf.transport.http.HTTPConduitFactory, org.apache.cxf.transport.ConduitInitiator]", "Cannot complete the install because one or more required items could not be found.", " Software being installed: BfR Internal Feature 1.0.0.201807201155 (de.bund.bfr.knime.internal.feature.feature.group 1.0.0.201807201155)", " Missing requirement: BfR Internal Feature 1.0.0.201807201155 (de.bund.bfr.knime.internal.feature.feature.group 1.0.0.201807201155) requires 'de.bund.br.knime.nodes.util 0.0.0' but it could not be found", "Application failed, log file location: /opt/knime_server/knime_executor/configuration/1538835430342.log", "Oct 06, 2018 4:17:49 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener unregister", "INFO: Removing the extensions for bundle 298", "Oct 06, 2018 4:17:49 PM org.apache.cxf.bus.osgi.CXFExtensionBundleListener unregister", "INFO: Removing the extensions for bundle 299"], "stdout": "CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot\nInstalling de.bund.bfr.knime.internal.feature.feature.group 1.0.0.201807201155.\nInstallation failed.", "stdout_lines": ["CompilerOracle: exclude javax/swing/text/GlyphView.getBreakSpot", "Installing de.bund.bfr.knime.internal.feature.feature.group 1.0.0.201807201155.", "Installation failed."]}
`

**Comment by miguelalba** [comment] 2018-10-08 09:41
This is not a bug of FSK-Lab but [the internal nodes](https://github.com/SiLeBAT/BfR-Internal). It should be reported there.

The problem is that the internal nodes are outdated due to last changes to FSK-Lab. A solution could be to integrate it into FSK-Lab and use a different update project so that it publishes it to the internal update site. These nodes are not meant for end users.

**Comment by llavall** [comment] 2018-10-08 09:47
@Miguel please move the ticket to another place if this is more convenient. 
Regarding the issue itself. If the node was not for the end user (Alex + BfR) what are you going to do know? I don't see why it should be part of FSK, as you explained above. Please, also inform Alex via Mail and put M. Filter and me CC.

**Comment by miguelalba** [comment] 2018-10-10 15:14
Fixed in 529f73309bcd49b3e52cec51e790d02028520bff

**Closed by miguelalba** 2018-10-10 15:14 UTC
Labels: blocking, bug, high priority
