### ISSUE TITLE
Change structure of the editor on model class

### ISSUE THREAD

**Issue by miguelalba** [SiLeBAT/FSK-Lab#411] opened 2020-04-16 15:20 UTC
When the mode class changes the entire GUI of the editor should change with the properties of the new model class. Compatible metadata should be kept.

![image](https://user-images.githubusercontent.com/19906968/79474302-8489bd80-8006-11ea-8d30-b89de7b1a94c.png)

**Comment by schuelet** [comment] 2021-03-03 17:34
@miguelalba Where are we on this one?

**Comment by schuelet** [comment] 2021-04-19 13:37
duplicate of #305

**Closed by schuelet** 2021-04-19 13:37 UTC
Labels: Feature, medium priority
