### ISSUE TITLE
Joiner does not work with certain models

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#840] opened 2021-04-11 12:02 UTC
the error is on the JavaScript side, the error message can not be copied.
Check the following workflow
knime://BfR-extern/FSKX_Testing/FSK-Lab_2.0/broken_workflows/testCampy_Joiner_fails

**Comment by ahmadswaid** [comment] 2021-04-11 17:49
@mfilter: the mentioned workflow contains only one reader connected to the joiner.

**Comment by mfilter** [comment] 2021-04-11 18:16
Yes, still the error should be reproducable. You can connect any other model to the second port if that helps.
>>> ahmadswaid ***@***.***> 11.04.21 19.49 Uhr >>>
@mfilter: the mentioned workflow contains only one reader connected to the joiner.


-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/SiLeBAT/FSK-Lab/issues/840#issuecomment-817345405
/// Wissenschaft im Dienst des Menschen ///
/// Science in the service of humanity ///

**Comment by ahmadswaid** [comment] 2021-04-21 21:19
I tried to reproduce the errors in knime both on windows and MacOS and that always succeeded.
seems to be fixed in development branch.
@schuelet: I'm closing this, please reopen if you see any errors related to this model.
<img width="1195" alt="Screenshot 2021-04-21 at 23 07 19" src="https://user-images.githubusercontent.com/4013295/115621118-5ebc8600-a2f6-11eb-99ea-922ccc11c49c.png">
<img width="631" alt="Screenshot 2021-04-21 at 23 15 36" src="https://user-images.githubusercontent.com/4013295/115621975-8cee9580-a2f7-11eb-842c-963b0a3d0381.png">

**Closed by ahmadswaid** 2021-04-21 21:19 UTC
Labels: Bug, high priority
