### ISSUE TITLE
Edit Parameter view opened from the new editor does not display the correct information

### ISSUE THREAD

**Issue by mfilter** [SiLeBAT/FSK-Lab#838] opened 2021-04-10 09:06 UTC
Got to https://knime.bfr.berlin/knime/webportal/space/FSK-Web/JoinerComponent_Petra_modified
select any of the models and click the "edit" symbol
in the editor view go to "Model math -> Parameter
edit any of the parameters in the model and check the information on Data type and Classification.
In the pop up window many parameters are wrongly labeled as "Constant" even though they are declared as Input or Output.
The same is true for the data type that is displayed. 
I did not check other fields, but this  must not happen.

**Comment by schuelet** [comment] 2021-04-10 09:32
@ahmadswaid to clarify, the issue is, that on opening the modal view of "edit parameter", the properties "classification" and "data type" are set to their default values (or first values in the list), i.e. for "data type", it is always set to INTEGER. This does not seem to occur on other fields using controlled vocabulary .

**Comment by schuelet** [comment] 2021-04-13 09:50
fixed as of https://app.zenhub.com/workspace/o/silebat/fsk-lab/issues/843 and  https://github.com/SiLeBAT/FSK-Lab/pull/846

**Closed by schuelet** 2021-04-13 09:50 UTC
Labels: Bug, high priority
